web:
    build: web
    ports:
        - "80:80"
    links:
        - query
query:
    build: backend
    ports:
        - "1500:1500"
    volumes:
        - /opt/lensing/data:/data
    environment:
        CONFIG: wikipediahistory
