web:
    build: web
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "80:80"
    restart: on-failure:10
query:
    build: backend
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "1500:1500"
    volumes:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - /opt/lensing/data:/data
    environment:
        CONFIG: wikipediahistory
    restart: on-failure:10
