version: '2'

services:
    web:
        volumes:
            - ./web:/opt/lensing
        logging:
            driver: "json-file"
            options: {}

    query:
        volumes:
            - ./backend:/opt/lensing
        logging:
            driver: "json-file"
            options: {}
