web:
    build: web
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "8080:80"
    restart: on-failure:10
    log_driver: "syslog"
    log_opt:
        syslog-tag: "web"
query:
    build: backend
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "1500:1500"
    volumes:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - /var/www/html/data/wikipedia/latest:/data
    environment:
        CONFIG: wikipediahistory
    restart: on-failure:10
    log_driver: "syslog"
    log_opt:
        syslog-tag: "query"
