version: '2'

services:
    web:
        environment:
            LENSING_BACKEND_URL: "http://localhost:1500"
        volumes:
            - ./web:/opt/lensing
        logging:
            driver: "json-file"
            options: {}

    query:
        environment:
            LENSING_BACKEND_URL: "http://localhost:1500"
        volumes:
            - ./backend:/opt/lensing
        logging:
            driver: "json-file"
            options: {}
