web:
    environment:
        LENSING_BACKEND_URL: "http://localhost:1500"
    volumes:
        - ./web:/opt/lensing
    log_driver: "json-file"
    log_opt: {}

query:
    environment:
        LENSING_BACKEND_URL: "http://localhost:1500"
    volumes:
        - ./backend:/opt/lensing
    log_driver: "json-file"
    log_opt: {}
