web:
    environment:
        LENSING_BACKEND_URL: "http://localhost:1500"
    log_driver: "json-file"

query:
    environment:
        LENSING_BACKEND_URL: "http://localhost:1500"
    log_driver: "json-file"

data:
    environment:
        LENSING_BACKEND_URL: "http://localhost:1500"
    log_driver: "json-file"
