web:
    build: web
    ports:
        - "80:80"
    links:
        - query
        - data
    volumes_from:
        - data
query:
    build: backend
    ports:
        - "1500:1500"
    volumes_from:
        - data
    environment:
        CONFIG: wikipediahistory
data:
    build: .
