web:
    build: web
    environment:
        # DO NOT CHANGE, UNLESS YOU MAKE THE SAME CHANGE EVERYWHERE
        LENSING_DB_URI: 'sqlite:////data/db/app.db'
    env_file:
        - ./config.env
        - ./keys.env
    restart: on-failure:10
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "8080:80"
    volumes_from:
        - data
    log_driver: "${LENSING_DOCKER_LOG_DRIVER}"

query:
    build: backend
    env_file:
        - ./config.env
    restart: on-failure:10
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "1500:1500"
    volumes_from:
        - data
    links:
        - redis
    log_driver: "${LENSING_DOCKER_LOG_DRIVER}"

data:
    build: .
    dockerfile: Dockerfile-data
    env_file:
        - ./config.env

redis:
    image: redis

#haproxy:
    #image: tutum/haproxy:0.2.1
    #links:
        #- query
    #ports:
        ## Format is HOST:CONTAINER
        ## Only change the HOST part
        #- "1500:80"
