# TO BE USED ON THE MAIN SERVER AS A STAGING SETUP

web-staging:
    extends:
        file: common.yml
        service: web
    labels:
        com.sfu.cs.lensingwikipedia.type: "staging"
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "8000:80"
    volumes_from:
        - data-staging
    log_driver: "syslog"
    log_opt:
        syslog-tag: "web"

query-staging:
    extends:
        file: common.yml
        service: query
    labels:
        com.sfu.cs.lensingwikipedia.environment: "staging"
    ports:
        # Format is HOST:CONTAINER
        # Only change the HOST part
        - "1501:1500"
    volumes_from:
        - data-staging
    log_driver: "syslog"
    log_opt:
        syslog-tag: "web"

data-staging:
    extends:
        file: common.yml
        service: data
    labels:
        com.sfu.cs.lensingwikipedia.type: "staging"
